// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef ROBOTMAP_H
#define ROBOTMAP_H
#include "WPILib.h"


/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
class RobotMap {
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	static std::shared_ptr<SpeedController> climbingClimberController;
	static std::shared_ptr<SpeedController> climbingWinchController;
	static std::shared_ptr<SpeedController> driveTrainFrontLeftController;
	static std::shared_ptr<SpeedController> driveTrainFrontRightController;
	static std::shared_ptr<SpeedController> driveTrainBackLeftController;
	static std::shared_ptr<SpeedController> driveTrainBackRightController;
	static std::shared_ptr<RobotDrive> driveTrainRobotDrive41;
	static std::shared_ptr<SpeedController> intakeRollerController;
	static std::shared_ptr<DoubleSolenoid> intakeIntakeMovementPneumatic;
	static std::shared_ptr<SpeedController> manipulatorManipulatorController;
	static std::shared_ptr<Solenoid> firingFirePneumatic0;
	static std::shared_ptr<Solenoid> firingFirePneumatic1;
	static std::shared_ptr<Solenoid> firingFirePneumatic2;
	static std::shared_ptr<Solenoid> firingFirePneumatic3;
	static std::shared_ptr<DoubleSolenoid> transmissionTransmissionPneumatic;
	static std::shared_ptr<Relay> flasherFlashlight;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

	static std::shared_ptr<ADXRS450_Gyro> gyro;

	static void init();
};
#endif
