// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef ROBOTMAP_H
#define ROBOTMAP_H
#include "WPILib.h"


/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
class RobotMap {
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	static std::shared_ptr<SpeedController> driveTrainLeftDrive1;
	static std::shared_ptr<SpeedController> driveTrainLeftDrive2;
	static std::shared_ptr<SpeedController> driveTrainRightDrive1;
	static std::shared_ptr<SpeedController> driveTrainRightDrive2;
	static std::shared_ptr<RobotDrive> driveTrainRobotDrive41;
	static std::shared_ptr<SpeedController> intakeAndManipulatorIntakeRoller;
	static std::shared_ptr<SpeedController> intakeAndManipulatorManipulator;
	static std::shared_ptr<SpeedController> grapplingHookClimber;
	static std::shared_ptr<SpeedController> grapplingHookWinch;
	static std::shared_ptr<Solenoid> catapultPneumaticsCatapult1;
	static std::shared_ptr<Solenoid> catapultPneumaticsCatapult2;
	static std::shared_ptr<Solenoid> catapultPneumaticsCatapult3;
	static std::shared_ptr<Solenoid> catapultPneumaticsCatapult4;
	static std::shared_ptr<DoubleSolenoid> transmissionShifter;
	static std::shared_ptr<DoubleSolenoid> intakePositionersIntakeRaiseLower;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

	static void init();
};
#endif
